### ISSUE TITLE
For more privacy, use invidio.us as an explanatory video on the web.

### ISSUE THREAD

**Issue by wuniversales** [runkod/runkod-app#6]
As the title says, for more privacy, use invidio.us as an explanatory video on the web.
I leave the code here...

`<iframe id='ivplayer' type='text/html' width='640' height='360' src='https://invidio.us/embed/abWsiwslrrc' frameborder='0'></iframe>`

regards

**Comment by talhasch** [comment]
@wuniversales  We will consider for future videos. Thanks.

**Comment by wuniversales** [comment]
invidio.us is a proxy for youtube, you don't have to upload the videos or anything like that again.
In fact this is your video on the web:
https://invidio.us/watch?v=abWsiwslrrc
regards
