### ISSUE TITLE
404 error is not displayed if file or directory does not exist

### ISSUE THREAD

**Issue by wuniversales** [runkod/runkod-app#7]
On each website, I have a 404.html file
Error 404 is not shown if the file or directory does not exist, instead it shows the previous available directory.

Example:
https://buscatope.runkodapps.com/
Show the main page of the web.

https://buscatope.runkodapps.com/route-invented
It should show 404.html instead of the main page since the directory does not exist.

**Comment by talhasch** [comment]
related to #8
